# .github/workflows/deploy.yml
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: Build with Maven
        run: mvn clean package
      - name: Docker Build
        run: docker build -t my-app:${{ github.sha }} .
      - name: Docker Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-app:${{ github.sha }}
      - name: Deploy to Server
        run: ssh user@server "docker pull my-app:${{ github.sha }} && docker run -d my-app:${{ github.sha }}"