# .github/workflows/deploy.yml
name: Deploy Spring Boot Application

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infra/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/infra.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'infra/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/infra.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Docker Build
        run: docker build -t elsevierdemo-api:${{ github.sha }} .

      # - name: Docker Push
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker push elsevierdemo-api:${{ github.sha }}

      # - name: Deploy to Server
      #   run: ssh user@server "docker pull elsevierdemo-api:${{ github.sha }} && docker run -d elsevier/elsevierdemo-api:${{ github.sha }}"